### ISSUE TITLE
bert先微调后白化，测试集相关系数下降

### ISSUE THREAD

**Issue by JaheimLee** [bojone/BERT-whitening#2]
如题，我先在bert-flow（avg-last-2问题已经做了统一）的代码上用cos相似度微调了一版bert，然后再用白化操作，测试集相关系数变低将近5个点。而先微调再训练flow，对微调后的bert依然有点提升效果。苏神有没有试过这种情况啊。

**Comment by bojone** [comment]
我感觉你对BERT-whitening的使用是不是有什么不当的地方。

BERT-whitening确实未必能超过BERT-flow，但感觉不至于差那么远～

**Comment by YangWangsky** [comment]
> 如题，我先在bert-flow（avg-last-2问题已经做了统一）的代码上用cos相似度微调了一版bert，然后再用白化操作，测试集相关系数变低将近5个点。而先微调再训练flow，对微调后的bert依然有点提升效果。苏神有没有试过这种情况啊。

Hi,  请教几个问题啊。 bert-flow的一系列实验，都是在bert不finetune只训练flow的基础上给出的吗？有点好奇你的实验，如果在下游任务finetune BERT（不用flow），结果会比固定bert只训练flow好么？其次你的第一个实验，“先在bert-flow（avg-last-2问题已经做了统一）的代码上用cos相似度微调了一版bert”，这里用了flow么？如果用了的话，flow的参数是随机初始化还是使用加载paper作者的参数？期待您的回复

**Comment by bojone** [comment]
> > 如题，我先在bert-flow（avg-last-2问题已经做了统一）的代码上用cos相似度微调了一版bert，然后再用白化操作，测试集相关系数变低将近5个点。而先微调再训练flow，对微调后的bert依然有点提升效果。苏神有没有试过这种情况啊。
> 
> Hi, 请教几个问题啊。 bert-flow的一系列实验，都是在bert不finetune只训练flow的基础上给出的吗？有点好奇你的实验，如果在下游任务finetune BERT（不用flow），结果会比固定bert只训练flow好么？其次你的第一个实验，“先在bert-flow（avg-last-2问题已经做了统一）的代码上用cos相似度微调了一版bert”，这里用了flow么？如果用了的话，flow的参数是随机初始化还是使用加载paper作者的参数？期待您的回复

BERT_base/large是没有finetune的，BERT_base/large-NLI是经过NLI数据集finetune的，但它们都没有在测试的7个数据集上进行finetune

**Comment by YangWangsky** [comment]
> > > 如题，我先在bert-flow（avg-last-2问题已经做了统一）的代码上用cos相似度微调了一版bert，然后再用白化操作，测试集相关系数变低将近5个点。而先微调再训练flow，对微调后的bert依然有点提升效果。苏神有没有试过这种情况啊。
> > 
> > 
> > Hi, 请教几个问题啊。 bert-flow的一系列实验，都是在bert不finetune只训练flow的基础上给出的吗？有点好奇你的实验，如果在下游任务finetune BERT（不用flow），结果会比固定bert只训练flow好么？其次你的第一个实验，“先在bert-flow（avg-last-2问题已经做了统一）的代码上用cos相似度微调了一版bert”，这里用了flow么？如果用了的话，flow的参数是随机初始化还是使用加载paper作者的参数？期待您的回复
> 
> BERT_base/large是没有finetune的，BERT_base/large-NLI是经过NLI数据集finetune的，但它们都没有在测试的7个数据集上进行finetune

hhh，肯定不能在测试集上finetune，谢谢您的回复。请问下“BERT_base/large-NLI是经过NLI数据集finetune的”，这个finetune是bert和flow同时训练吗？

**Comment by bojone** [comment]
有监督只训练bert，flow只用于无监督训练。

**Comment by JaheimLee** [comment]
> > > > 如题，我先在bert-flow（avg-last-2问题已经做了统一）的代码上用cos相似度微调了一版bert，然后再用白化操作，测试集相关系数变低将近5个点。而先微调再训练flow，对微调后的bert依然有点提升效果。苏神有没有试过这种情况啊。
> > > 
> > > 
> > > Hi, 请教几个问题啊。 bert-flow的一系列实验，都是在bert不finetune只训练flow的基础上给出的吗？有点好奇你的实验，如果在下游任务finetune BERT（不用flow），结果会比固定bert只训练flow好么？其次你的第一个实验，“先在bert-flow（avg-last-2问题已经做了统一）的代码上用cos相似度微调了一版bert”，这里用了flow么？如果用了的话，flow的参数是随机初始化还是使用加载paper作者的参数？期待您的回复
> > 
> > 
> > BERT_base/large是没有finetune的，BERT_base/large-NLI是经过NLI数据集finetune的，但它们都没有在测试的7个数据集上进行finetune
> 
> hhh，肯定不能在测试集上finetune，谢谢您的回复。请问下“BERT_base/large-NLI是经过NLI数据集finetune的”，这个finetune是bert和flow同时训练吗？

这个我还真尝试了一下，如果你要刷分的话，你在测试数据的训练集上fintune一个bert，然后用整个测试数据训练flow，相似系数还能涨一点

**Comment by YangWangsky** [comment]
明白了，谢谢两位。假设我有充足的训练集，且训练的时候是以cosine similarity算loss进行优化的，那么可能flow和PCA白化的思想就没什么用了？因为可能训练的时候，模型已经学到了各个维度需要正交的知识？

**Comment by BigRabbit71** [comment]
> 有监督只训练bert，flow只用于无监督训练。

Hi, 请教一个脑洞问题，如果把flow（或白化）的结果再次回传给BERT帮助下游任务的finetune（比如在一个training batch中做白化，用变换后的vector做similarity的度量），会不会能够进一步地帮助model学习到每一维上的正交性？

**Comment by bojone** [comment]
如果你的训练集和测试集是同分布的，那么就没什么用了；但如果训练集跟测试集仅仅是同任务但不同分布的，那么whitening还是可能有帮助的。

比如simbert，可以认为它在相似度数据集上做了有监督的预训练（相似度是cos），但是如果直接用到lcqmc中测试，我发现whitening还是能提升一点效果，因为simbert的训练集跟lcqmc并不是同分布的，但任务可以说是一致的。
