### ISSUE TITLE
PCA变换之后的正则化操作

### ISSUE THREAD

**Issue by zwq0605** [bojone/BERT-whitening#5]
https://github.com/bojone/BERT-whitening/blob/b4a44cc0adaf11cc7380366a5009173ae7763194/demo.py#L125

请问下做了PCA变换之后为什么还会有一个正则化操作呢？我看了几次代码感觉这像是一个layer normalization的操作，有点不理解，如果这里做正则化不是应该直接做normalization吗？

**Comment by bojone** [comment]
算cos值不是要归一化吗。。。。

**Comment by zwq0605** [comment]
感谢解答~之前没看到后面的操作所以误会了，那如果我想用bert-whitening提取sentence-level的embedding的话，应该就不用做这个归一化操作了吧？

**Comment by TestNLP** [comment]
> 感谢解答~之前没看到后面的操作所以误会了，那如果我想用bert-whitening提取sentence-level的embedding的话，应该就不用做这个归一化操作了吧？

![image](https://user-images.githubusercontent.com/23632648/114337585-f0542700-9b83-11eb-8246-03d30d469cb4.png)

你是通过这个函数计算的吧？我传入bert转过的768维度的句向量（一个句子的句向量）， cov = np.cov(vecs.T)报错啊，感觉这个好像不能直接计算一个句子的句向量，我是用来线上推断的

**Comment by TestNLP** [comment]
> https://github.com/bojone/BERT-whitening/blob/b4a44cc0adaf11cc7380366a5009173ae7763194/demo.py#L125
> 
> 请问下做了PCA变换之后为什么还会有一个正则化操作呢？我看了几次代码感觉这像是一个layer normalization的操作，有点不理解，如果这里做正则化不是应该直接做normalization吗？

我认为如果只是提取一个句子的句向量，只需要下面这样既可
![image](https://user-images.githubusercontent.com/23632648/114337685-27c2d380-9b84-11eb-8dee-8e1446368a30.png)

**Comment by zwq0605** [comment]
> > https://github.com/bojone/BERT-whitening/blob/b4a44cc0adaf11cc7380366a5009173ae7763194/demo.py#L125
> > 
> > 请问下做了PCA变换之后为什么还会有一个正则化操作呢？我看了几次代码感觉这像是一个layer normalization的操作，有点不理解，如果这里做正则化不是应该直接做normalization吗？
> 
> 我认为如果只是提取一个句子的句向量，只需要下面这样既可
> ![image](https://user-images.githubusercontent.com/23632648/114337685-27c2d380-9b84-11eb-8dee-8e1446368a30.png)

是的，我就是这么做了，你上面说的报错我不知道咋回事，可能是维度没对上？我这边没问题

**Comment by TestNLP** [comment]
> > > https://github.com/bojone/BERT-whitening/blob/b4a44cc0adaf11cc7380366a5009173ae7763194/demo.py#L125
> > > 
> > > 请问下做了PCA变换之后为什么还会有一个正则化操作呢？我看了几次代码感觉这像是一个layer normalization的操作，有点不理解，如果这里做正则化不是应该直接做normalization吗？
> > 
> > 
> > 我认为如果只是提取一个句子的句向量，只需要下面这样既可
> > ![image](https://user-images.githubusercontent.com/23632648/114337685-27c2d380-9b84-11eb-8dee-8e1446368a30.png)
> 
> 是的，我就是这么做了，你上面说的报错我不知道咋回事，可能是维度没对上？我这边没问题

加个微信，18392408198，详聊

**Comment by TestNLP** [comment]
![image](https://user-images.githubusercontent.com/23632648/114650685-41475500-9d15-11eb-8423-2fdaf0b092bf.png)


我在LCQMC数据集上跑了一下，如上所示，PCA性能感觉还是有不少下降的啊，截图第一个是原生态BERT，效果确实不行；后续三个是没有白化，白化维度256和768的情况，你们的实验效果是这样的吗？这个符合预期吗？

**Comment by zwq0605** [comment]
我是直接用来提取句向量用于下游分类任务的，思路是认为在“各向同性”的向量空间中不同样本特征的距离度量更加合理，下游任务对两个样本的差异能够更准确地建模，但实际上白化操作对下游任务几乎没什么提升，可能这个方法还是更适合于比较相似度的任务吧，不过值得一提的是拿来做降维效果还是不错的
