### ISSUE TITLE
SBERT+whitening

### ISSUE THREAD

**Issue by xtdx** [bojone/BERT-whitening#7]
paper中提到了SBERT+whitening,怎么加whitening？SBERT是e2e的进行二分类或者回归，而whiteing需要在已知所有句子emb时计算

**Comment by bojone** [comment]
那是你还没有认真了解SBERT。

所谓“e2e的进行二分类或者回归”，那只是SBERT的训练方式，训练完成后，把最后的分类层扔掉，当作一个特征（句向量）提取器来用的。

**Comment by xtdx** [comment]
那就明白了。paper里说的有监督，跟whitening其实没有关系
